// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjDB2Dc_XMLYkTh9f73Pn0lqUURAfmF1o',
    appId: '1:1013923326347:web:c092cdaee6e5e97ac3678e',
    messagingSenderId: '1013923326347',
    projectId: 'coffeeshop-f03b5',
    authDomain: 'coffeeshop-f03b5.firebaseapp.com',
    storageBucket: 'coffeeshop-f03b5.firebasestorage.app',
    measurementId: 'G-TRQLJ1TZ7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzs95nxKyrzEQbZvqJyvnI9KQjlAKci-k',
    appId: '1:1013923326347:android:52af04abcc368bfcc3678e',
    messagingSenderId: '1013923326347',
    projectId: 'coffeeshop-f03b5',
    storageBucket: 'coffeeshop-f03b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_nA4-15ofv7ijrfWkvbRzVk8xkaTTU10',
    appId: '1:1013923326347:ios:7d1ab2e778e64a32c3678e',
    messagingSenderId: '1013923326347',
    projectId: 'coffeeshop-f03b5',
    storageBucket: 'coffeeshop-f03b5.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShopAdminDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_nA4-15ofv7ijrfWkvbRzVk8xkaTTU10',
    appId: '1:1013923326347:ios:7d1ab2e778e64a32c3678e',
    messagingSenderId: '1013923326347',
    projectId: 'coffeeshop-f03b5',
    storageBucket: 'coffeeshop-f03b5.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShopAdminDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjDB2Dc_XMLYkTh9f73Pn0lqUURAfmF1o',
    appId: '1:1013923326347:web:977b78bca1d758fec3678e',
    messagingSenderId: '1013923326347',
    projectId: 'coffeeshop-f03b5',
    authDomain: 'coffeeshop-f03b5.firebaseapp.com',
    storageBucket: 'coffeeshop-f03b5.firebasestorage.app',
    measurementId: 'G-D2KDEMXLC1',
  );
}
