import 'package:equatable/equatable.dart';
import 'cart_item.dart';

class OrderDetails extends Equatable {
  final String id; // Nullable because it's generated by Firestore
  final List<CartItem> items;
  final double totalPrice;
  final String userId;
  final DateTime timestamp;
  final int pointsRedeemed; // <-- أضف هذا
  final double discountAmount; // <-- أضف هذا

  const OrderDetails({
    required this.id,
    required this.items,
    required this.totalPrice,
    required this.userId,
    required this.timestamp,
    this.pointsRedeemed = 0, // <-- أضف قيمة افتراضية
    this.discountAmount = 0.0, // <-- أضف قيمة افتراضية
  });

  @override
  List<Object?> get props => [
    id,
    items,
    totalPrice,
    userId,
    timestamp,
    pointsRedeemed,
    discountAmount,
  ];
}
